import { useEffect, useMemo, useState } from 'react';
import { OrganizerLayout } from '../../layouts/OrganizerLayout';
import { adminAssignSequence, adminUpsertRouteItem, getConvergenceAdminDashboard, getConvergenceAudit, getConvergenceSequences, setConvergenceGame, upsertConvergenceSequence, type ConvergenceSequence } from '../../lib/db';

type TeamRow={id:string;name:string;track_id:string;status:string;stage:number;step:string;warnings:number;stage3_rank:number|null;stage6_rank:number|null;clue9_rank:number|null;started_at:string|null;last_action_at:string|null};
const STEPS=['HAND_IN','STICKER_1','STICKER_2','ANSWER_2','RIDDLE_4','STICKER_4','STICKER_5','ANSWER_5','RIDDLE_7','STICKER_7','CLUE_8','CLUE_9'];
const STAGES=Array.from({length:10},(_,i)=>i+1);

export function ConvergenceControlScreen(){
 const [stage,setStage]=useState(1); const [running,setRunning]=useState(false); const [teams,setTeams]=useState<TeamRow[]>([]);
 const [selectedTeam,setSelectedTeam]=useState<TeamRow|null>(null); const [sequences,setSequences]=useState<ConvergenceSequence[]>([]);
 const [dragged,setDragged]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const [routeStep,setRouteStep]=useState('HAND_IN'); const [route,setRoute]=useState({title:'',body:'',instruction:'',physicalLocation:'',stickerImageUrl:'',clueImageUrl:'',code:'',answer:''});
 const [sequenceId,setSequenceId]=useState<string|null>(null); const [sequenceName,setSequenceName]=useState(''); const [sequenceJson,setSequenceJson]=useState('{\n  "items": [],\n  "final_riddle": {"title":"Final Riddle","body":""}\n}');
 const [audit,setAudit]=useState<Array<{id:number;event_type:string;stage:number|null;step_key:string|null;created_at:string}>>([]);

 const load=async()=>{try{const d=await getConvergenceAdminDashboard();setStage(d.game.current_stage);setRunning(d.game.running);setTeams(d.teams as TeamRow[]);setSequences(await getConvergenceSequences());}catch(e){setMessage(e instanceof Error?e.message:'Unable to load control data.')}};
 useEffect(()=>{void load();const i=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(i)},[]);
 const counts=useMemo(()=>teams.reduce((a,t)=>(a[t.status]=(a[t.status]||0)+1,a),{} as Record<string,number>),[teams]);
 const control=async(nextStage:number,nextRunning:boolean)=>{setBusy(true);setMessage('');try{await setConvergenceGame(nextStage,nextRunning);await load();setMessage(nextRunning?'Stage '+nextStage+' resumed.':'Game paused.')}catch(e){setMessage(e instanceof Error?e.message:'Control action failed.')}finally{setBusy(false)}};
 const assign=async(teamId:string,seqId:string)=>{setBusy(true);try{await adminAssignSequence(teamId,seqId);await load();setMessage('Sequence assigned. The team remains paused until resume.')}catch(e){setMessage(e instanceof Error?e.message:'Assignment failed.')}finally{setBusy(false)}};
 const saveRoute=async()=>{if(!selectedTeam)return;setBusy(true);try{await adminUpsertRouteItem({teamId:selectedTeam.id,stepKey:routeStep,title:route.title,body:route.body,instruction:route.instruction,physicalLocation:route.physicalLocation,stickerImageUrl:route.stickerImageUrl,clueImageUrl:route.clueImageUrl,code:route.code||undefined,answer:route.answer||undefined});setMessage('Route content saved securely.')}catch(e){setMessage(e instanceof Error?e.message:'Route save failed.')}finally{setBusy(false)}};
 const saveSequence=async()=>{setBusy(true);try{const parsed=JSON.parse(sequenceJson) as Record<string,unknown>;const id=await upsertConvergenceSequence(sequenceId,sequenceName,parsed);setSequenceId(id);await load();setMessage('Sequence saved.')}catch(e){setMessage(e instanceof Error?e.message:'Sequence JSON is invalid.')}finally{setBusy(false)}};
 const loadAudit=async(teamId:string|null)=>{try{const a=await getConvergenceAudit(teamId);setAudit(a.map(x=>({id:x.id,event_type:x.event_type,stage:x.stage,step_key:x.step_key,created_at:x.created_at})))}catch(e){setMessage(e instanceof Error?e.message:'Audit load failed.')}};

 return <OrganizerLayout title="Convergence Control">
  <div className="space-y-6">
   {message&&<div className="border border-gold/20 bg-gold/5 text-gold px-4 py-3 rounded text-sm">{message}</div>}
   <div className="grid grid-cols-2 md:grid-cols-7 gap-2">{Object.entries({TOTAL:teams.length,ACTIVE:counts.ACTIVE||0,PAUSED:counts.PAUSED||0,PROMOTED:counts.PROMOTED||0,ELIMINATED:counts.ELIMINATED||0,FINALISTS:counts.FINALIST||0,WINNER:counts.WINNER||0}).map(([k,v])=><div key={k} className="bg-[#111] border border-gray-800 rounded p-3"><div className="text-[10px] text-gray-500 uppercase">{k}</div><div className="text-xl text-white mt-1">{v}</div></div>)}</div>
   <section className="bg-[#111] border border-gray-800 rounded p-5"><div className="flex flex-wrap items-end gap-3"><div><label className="block text-[10px] uppercase text-gray-500 mb-1">Global stage</label><select value={stage} onChange={e=>setStage(Number(e.target.value))} className="bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-white">{STAGES.map(s=><option key={s}>{s}</option>)}</select></div><button disabled={busy} onClick={()=>void control(stage,true)} className="bg-green-600 text-white px-4 py-2 rounded text-sm font-semibold">{running?'Resume / Sync':'Start / Resume'} Stage {stage}</button><button disabled={busy} onClick={()=>void control(stage,false)} className="border border-red-900 text-red-300 px-4 py-2 rounded text-sm">Pause Game</button></div><p className="text-xs text-gray-600 mt-3">Stage 1 starts waiting teams. Stage 4 and Stage 7 activate eligible promoted teams. Cutoffs are enforced server-side and pause the game.</p></section>
   {stage===4&&<section className="bg-[#111] border border-gray-800 rounded p-5"><h3 className="text-white font-semibold">Stage 4 — Route Assignment</h3><p className="text-xs text-gray-500 mb-4">Drag a prepared sequence onto a promoted team.</p><div className="grid lg:grid-cols-[280px_1fr] gap-4"><div className="space-y-2">{sequences.map(s=><div key={s.id} draggable onDragStart={()=>setDragged(s.id)} onClick={()=>{setSequenceId(s.id);setSequenceName(s.name);setSequenceJson(JSON.stringify(s.payload,null,2))}} className="p-3 bg-[#171717] border border-gray-700 rounded cursor-grab"><div className="text-sm text-white">{s.name}</div><div className="text-[10px] text-gray-500 mt-1">{s.assigned_team_id?'Assigned':'Unassigned'}</div></div>)}</div><div className="grid md:grid-cols-2 gap-2">{teams.filter(t=>t.status==='PROMOTED').map(t=><div key={t.id} onDragOver={e=>e.preventDefault()} onDrop={()=>dragged&&void assign(t.id,dragged)} className="p-3 border border-gray-800 rounded bg-black/20"><div className="flex justify-between"><span className="text-white">{t.name}</span><span className="text-xs text-gold">{t.track_id}</span></div><div className="text-[10px] text-gray-500 mt-1">Stage 4 assignment · Rank {t.stage3_rank??'—'}</div></div>)}</div></div><div className="mt-5 border-t border-gray-800 pt-4 grid md:grid-cols-[180px_1fr] gap-3"><input value={sequenceName} onChange={e=>setSequenceName(e.target.value)} placeholder="Sequence name" className="bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-white text-sm"/><textarea value={sequenceJson} onChange={e=>setSequenceJson(e.target.value)} rows={8} className="bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-white font-mono text-xs"/><button onClick={()=>void saveSequence()} disabled={!sequenceName||busy} className="bg-gold text-black px-4 py-2 rounded text-sm font-semibold md:col-start-2">Save Sequence</button></div></section>}
   <section className="bg-[#111] border border-gray-800 rounded p-5"><div className="flex flex-wrap items-center gap-2 mb-4"><h3 className="text-white font-semibold mr-2">Team Route Editor</h3><select value={selectedTeam?.id||''} onChange={e=>setSelectedTeam(teams.find(t=>t.id===e.target.value)||null)} className="bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-sm text-white"><option value="">Select team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name} · {t.track_id}</option>)}</select><select value={routeStep} onChange={e=>setRouteStep(e.target.value)} className="bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-sm text-white">{STEPS.map(s=><option key={s}>{s}</option>)}</select></div><div className="grid md:grid-cols-2 gap-3">{[['title','Title'],['body','Body / Riddle / Clue'],['instruction','Instruction'],['physicalLocation','Physical location'],['stickerImageUrl','Sticker image URL'],['clueImageUrl','Clue image URL'],['code','Physical code'],['answer','Answer / 7-digit answer']].map(([key,label])=><label key={key} className="text-[10px] uppercase text-gray-500">{label}<textarea rows={key==='body'?4:2} value={route[key as keyof typeof route]} onChange={e=>setRoute({...route,[key]:e.target.value})} className="mt-1 w-full bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-white text-sm"/></label>)}</div><button disabled={!selectedTeam||busy} onClick={()=>void saveRoute()} className="mt-4 bg-gold text-black px-4 py-2 rounded text-sm font-semibold">Save Route Item</button></section>
   <section className="bg-[#111] border border-gray-800 rounded p-5"><div className="flex items-center justify-between mb-3"><h3 className="text-white font-semibold">Live Teams</h3><button onClick={()=>void load()} className="text-xs text-gold">Refresh</button></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="text-[10px] uppercase text-gray-500"><tr><th className="text-left py-2">Team</th><th>Track</th><th>Stage</th><th>Step</th><th>Status</th><th>Last Action</th></tr></thead><tbody>{teams.map(t=><tr key={t.id} className="border-t border-gray-900 cursor-pointer hover:bg-white/[.02]" onClick={()=>{setSelectedTeam(t);void loadAudit(t.id)}}><td className="py-3 text-white">{t.name}</td><td className="text-center text-gold">{t.track_id}</td><td className="text-center">{t.stage}</td><td className="text-center text-xs text-gray-400">{t.step}</td><td className="text-center text-xs">{t.status}</td><td className="text-right text-xs text-gray-500">{t.last_action_at?new Date(t.last_action_at).toLocaleTimeString():'—'}</td></tr>)}</tbody></table></div></section>
   {audit.length>0&&<section className="bg-[#111] border border-gray-800 rounded p-5"><h3 className="text-white font-semibold mb-3">Audit Trail</h3>{audit.map(a=><div key={a.id} className="flex justify-between gap-4 py-2 border-b border-gray-900 text-xs"><span className="text-gray-300">{a.event_type} · {a.step_key||'—'}</span><span className="text-gray-500">{new Date(a.created_at).toLocaleString()}</span></div>)}</section>}
  </div>
 </OrganizerLayout>;
}
