import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Download, Edit3, Plus, RefreshCw, Save, Trash2, Upload, Users, X } from 'lucide-react';
import { OrganizerLayout } from '../../layouts/OrganizerLayout';
import { deleteOrganizerTeam, getOrganizerProfile, getOrganizerTeamMembers, getOrganizerTeams, importOrganizerTeams, upsertOrganizerTeam, type OrganizerProfile, type OrganizerTeam } from '../../lib/db';

const TRACKS = ['A', 'B', 'C', 'D', 'TEST'] as const;
type TrackId = typeof TRACKS[number];
type Member = { name: string; email: string; phone: string };

function headerKey(value: string) { return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, ''); }
function csvRows(text: string) {
  const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false;
  for (let i = 0; i < text.length; i += 1) { const ch = text[i]; if (ch === '"') { if (quoted && text[i + 1] === '"') { cell += '"'; i += 1; } else quoted = !quoted; } else if (ch === ',' && !quoted) { row.push(cell); cell = ''; } else if ((ch === '\n' || ch === '\r') && !quoted) { if (ch === '\r' && text[i + 1] === '\n') i += 1; row.push(cell); if (row.some(v => v.trim())) rows.push(row); row = []; cell = ''; } else cell += ch; }
  if (cell || row.length) { row.push(cell); if (row.some(v => v.trim())) rows.push(row); } return rows;
}
function parseImport(text: string) {
  const table = csvRows(text); if (table.length < 2) throw new Error('CSV must contain headers and at least one team.');
  const headers = table[0].map(headerKey); const find = (...keys: string[]) => keys.map(headerKey).map(k => headers.indexOf(k)).find(i => i >= 0) ?? -1;
  const teamI = find('team_name', 'team', 'name'); const passI = find('password', 'team_password', 'login_password'); const trackI = find('track_id', 'track', 'track_name');
  const memberI = find('member_name', 'participant_name', 'participant', 'member'); const emailI = find('member_email', 'participant_email', 'email'); const phoneI = find('member_phone', 'participant_phone', 'phone', 'mobile');
  if (teamI < 0 || trackI < 0) throw new Error('CSV requires Team Name and Track columns.');
  const grouped = new Map<string, { team_name: string; password: string; track_id: string; members: Member[] }>(); let skipped = 0;
  for (const cells of table.slice(1)) { const name = (cells[teamI] || '').trim(); const track = (cells[trackI] || '').trim().toUpperCase(); if (!name || !track) { skipped += 1; continue; } if (!TRACKS.includes(track as TrackId)) throw new Error(`Unknown track "${track}" for ${name}.`); const key = `${track}::${name.toLowerCase()}`; const entry = grouped.get(key) ?? { team_name: name, password: passI >= 0 ? (cells[passI] || '').trim() : '', track_id: track, members: [] }; const memberName = memberI >= 0 ? (cells[memberI] || '').trim() : ''; if (memberName) entry.members.push({ name: memberName, email: emailI >= 0 ? (cells[emailI] || '').trim() : '', phone: phoneI >= 0 ? (cells[phoneI] || '').trim() : '' }); grouped.set(key, entry); }
  return { rows: [...grouped.values()], skipped };
}
function downloadTemplate() { const csv = 'team_name,password,track_id,member_name,member_email,member_phone\nTeam Alpha,Alpha@123,A,Alice Example,alice@example.com,9876543210\nTeam Alpha,Alpha@123,A,Bob Example,bob@example.com,9876543211\nTeam Beta,Beta@123,B,Charlie Example,charlie@example.com,9876543212\n'; const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const a = document.createElement('a'); a.href = url; a.download = 'convergence-participant-teams-template.csv'; a.click(); URL.revokeObjectURL(url); }

export function ParticipantTeamsManagerScreen() {
  const [profile, setProfile] = useState<OrganizerProfile | null>(null); const [teams, setTeams] = useState<OrganizerTeam[]>([]); const [selectedTrack, setSelectedTrack] = useState<TrackId | 'ALL'>('ALL');
  const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<OrganizerTeam | null>(null); const [name, setName] = useState(''); const [password, setPassword] = useState(''); const [track, setTrack] = useState<TrackId>('A'); const [members, setMembers] = useState<Member[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  const visibleTracks = useMemo(() => profile?.track_id ? [profile.track_id as TrackId] : TRACKS, [profile]); const visibleTeams = selectedTrack === 'ALL' ? teams : teams.filter(t => t.track_id === selectedTrack);
  const load = async () => { setLoading(true); try { const p = await getOrganizerProfile(); setProfile(p); const scoped = p?.track_id ?? (selectedTrack === 'ALL' ? null : selectedTrack); setTeams(await getOrganizerTeams(scoped)); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load teams.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [selectedTrack]);
  const closeForm = () => { setFormOpen(false); setEditing(null); setName(''); setPassword(''); setMembers([]); };
  const openCreate = () => { setFormOpen(true); setEditing(null); setName(''); setPassword(''); setTrack((profile?.track_id as TrackId) || 'A'); setMembers([]); setError(''); setMessage(''); };
  const openEdit = async (team: OrganizerTeam) => { setFormOpen(true); setEditing(team); setName(team.name); setPassword(''); setTrack(team.track_id as TrackId); setError(''); setMessage(''); const current = await getOrganizerTeamMembers(team.id); setMembers(current.map(m => ({ name: m.name, email: m.email || '', phone: m.phone || '' }))); };
  const addMember = () => setMembers(v => [...v, { name: '', email: '', phone: '' }]); const updateMember = (i: number, key: keyof Member, value: string) => setMembers(v => v.map((m, n) => n === i ? { ...m, [key]: value } : m)); const removeMember = (i: number) => setMembers(v => v.filter((_, n) => n !== i));
  const save = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { await upsertOrganizerTeam({ id: editing?.id, name, password, trackId: track, members: members.filter(m => m.name.trim()) }); setMessage(editing ? 'Team updated and synced to Supabase.' : 'Team created and synced to Supabase.'); closeForm(); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save team.'); } finally { setBusy(false); } };
  const remove = async (team: OrganizerTeam) => { if (!confirm(`Remove ${team.name}? This removes its hunt progress and active sessions too.`)) return; setBusy(true); try { await deleteOrganizerTeam(team.id); setMessage('Team removed from Supabase.'); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to remove team.'); } finally { setBusy(false); } };
  const importCsv = async (e: ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; setBusy(true); setError(''); try { const parsed = parseImport(await file.text()); if (!parsed.rows.length) throw new Error('No valid team rows found.'); const result = await importOrganizerTeams(parsed.rows); setMessage(`Import complete: ${result.created} created, ${result.updated} updated, ${result.processed} processed${parsed.skipped ? `, ${parsed.skipped} skipped` : ''}.`); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'CSV import failed.'); } finally { setBusy(false); e.target.value = ''; } };

  return <OrganizerLayout title="Participant Teams"><div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-gray-400 text-sm">Import your registration CSV and keep the participant teams synchronized with Supabase.</p><p className="text-gray-600 text-xs mt-1">Repeated team rows are grouped; each participant row becomes a team member.</p></div><div className="flex flex-wrap gap-2"><button onClick={downloadTemplate} className="flex items-center gap-2 border border-gray-700 px-3 py-2 rounded text-sm text-gray-300"><Download className="w-4 h-4" /> Template</button><button onClick={() => fileRef.current?.click()} disabled={busy} className="flex items-center gap-2 bg-gold text-black px-3 py-2 rounded text-sm font-semibold"><Upload className="w-4 h-4" /> Import CSV</button><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={importCsv} className="hidden" /><button onClick={openCreate} disabled={busy} className="flex items-center gap-2 border border-gold/50 text-gold px-3 py-2 rounded text-sm"><Plus className="w-4 h-4" /> Add Team</button><button onClick={() => void load()} disabled={busy} className="p-2 border border-gray-700 rounded text-gray-400"><RefreshCw className="w-4 h-4" /></button></div></div>
    {message && <div className="border border-green-900 bg-green-950/30 text-green-300 px-4 py-3 rounded text-sm">{message}</div>}{error && <div className="border border-red-900 bg-red-950/30 text-red-300 px-4 py-3 rounded text-sm">{error}</div>}
    <div className="flex flex-wrap gap-2">{!profile?.track_id && <button onClick={() => setSelectedTrack('ALL')} className={`px-4 py-2 rounded text-sm ${selectedTrack === 'ALL' ? 'bg-gold text-black' : 'bg-[#151515] text-gray-400'}`}>All Tracks</button>}{visibleTracks.map(t => <button key={t} onClick={() => setSelectedTrack(t)} className={`px-4 py-2 rounded text-sm ${selectedTrack === t ? 'bg-gold text-black' : 'bg-[#151515] text-gray-400'}`}>Track {t}</button>)}</div>
    {formOpen && <form onSubmit={save} className="bg-[#111] border border-gray-800 rounded p-5 space-y-4"><div className="flex justify-between"><h3 className="text-white font-semibold">{editing ? 'Edit Team' : 'Add Team'}</h3><button type="button" onClick={closeForm}><X className="w-4 h-4 text-gray-500" /></button></div><div className="grid md:grid-cols-3 gap-3"><label className="text-xs text-gray-500 uppercase">Team name<input value={name} onChange={e => setName(e.target.value)} required className="mt-1 w-full bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-white" /></label><label className="text-xs text-gray-500 uppercase">Password<input value={password} onChange={e => setPassword(e.target.value)} type="text" placeholder={editing ? 'Leave blank to keep current' : 'Required for login'} required={!editing} className="mt-1 w-full bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-white" /></label><label className="text-xs text-gray-500 uppercase">Track<select value={track} onChange={e => setTrack(e.target.value as TrackId)} disabled={Boolean(profile?.track_id)} className="mt-1 w-full bg-[#1a1a1a] border border-gray-700 rounded px-3 py-2 text-white">{visibleTracks.map(t => <option key={t} value={t}>{t}</option>)}</select></label></div><div className="space-y-2"><div className="flex items-center justify-between"><h4 className="text-sm text-gray-300 flex items-center gap-2"><Users className="w-4 h-4" /> Participants ({members.length})</h4><button type="button" onClick={addMember} className="text-xs text-gold">+ Add participant</button></div>{members.map((m,i) => <div key={`${i}-${m.name}`} className="grid grid-cols-1 md:grid-cols-[1fr_1fr_1fr_auto] gap-2"><input value={m.name} onChange={e => updateMember(i,'name',e.target.value)} placeholder="Name" className="bg-[#1a1a1a] border border-gray-700 rounded px-2 py-2 text-sm" /><input value={m.email} onChange={e => updateMember(i,'email',e.target.value)} placeholder="Email" className="bg-[#1a1a1a] border border-gray-700 rounded px-2 py-2 text-sm" /><input value={m.phone} onChange={e => updateMember(i,'phone',e.target.value)} placeholder="Phone" className="bg-[#1a1a1a] border border-gray-700 rounded px-2 py-2 text-sm" /><button type="button" onClick={() => removeMember(i)} className="p-2 text-red-400"><X className="w-4 h-4" /></button></div>)}</div><div className="flex gap-2"><button type="submit" disabled={busy} className="flex items-center gap-2 bg-gold text-black px-4 py-2 rounded font-semibold text-sm"><Save className="w-4 h-4" /> Save & Sync</button><button type="button" onClick={closeForm} className="px-4 py-2 border border-gray-700 rounded text-sm">Cancel</button></div></form>}
    <div className="bg-[#111] border border-gray-800 rounded overflow-hidden"><div className="hidden md:grid grid-cols-[1fr_120px_120px_120px] gap-3 px-4 py-3 border-b border-gray-800 text-xs uppercase tracking-wider text-gray-500"><span>Team</span><span>Track</span><span>Participants</span><span className="text-right">Actions</span></div>{loading ? <div className="p-8 text-center text-gray-600">Loading teams…</div> : visibleTeams.length === 0 ? <div className="p-8 text-center text-gray-600">No participant teams yet.</div> : visibleTeams.map(t => <div key={t.id} className="grid grid-cols-1 md:grid-cols-[1fr_120px_120px_120px] gap-2 md:gap-3 items-center px-4 py-3 border-b border-gray-900 last:border-0"><div className="text-white font-medium">{t.name}</div><div className="text-gray-400">Track {t.track_id}</div><div className="text-gray-400">{t.member_count} participant{t.member_count === 1 ? '' : 's'}</div><div className="flex md:justify-end gap-1"><button onClick={() => void openEdit(t)} disabled={busy} className="p-2 text-gray-400 hover:text-gold"><Edit3 className="w-4 h-4" /></button><button onClick={() => void remove(t)} disabled={busy} className="p-2 text-gray-400 hover:text-red-400"><Trash2 className="w-4 h-4" /></button></div></div>)}</div>
  </div></OrganizerLayout>;
}
